Repository adambard/learnxinyminutes-docs, pull requests merged in 2018-11, with the labels that each got.

#3349 [sql/en] Adding SQL entry
  sql.html.markdown
Labels: work in progress

#3345 [lambda-calculus/es-es] Translate Lambda Calculus to es_ES
  es-es/lambda-calculus-es.html.markdown
Labels: awaiting response, translation, work in progress

#3364 [csharp/pt-br] Update csharp-pt.html.markdown
  pt-br/csharp-pt.html.markdown
Labels: in review, translation update

#3152 [markdown/zh-cn] Update Chinese translation
  zh-cn/markdown-cn.html.markdown
Labels: translation update, work in progress

#3346 [pascal/es-es] Translate Pascal to es_ES
  es-es/pascal-es.html.markdown
Labels: awaiting response, translation, work in progress

#3363 [coldfusion/es-es] Translate ColdFusion to es_ES
  es-es/coldfusion-es.html.markdown
Labels: in review, translation, work in progress

#3389 [powershell/en] add list syntax example
  powershell.html.markdown
Labels: in review

#3398 [processing/en] Fix build error and styling
  processing.html.markdown
Labels: in review

#3403 [dart/zh-cn]Fix bool convert of chinese version.
  zh-cn/dart-cn.html.markdown
Labels: in review

#3402 [ansible/en] Cleaning up further
  ansible.html.markdown
Labels: in review

#3404 [M (MUMPS)/en] Add M/MUMPS language
  m.html.markdown
Labels: in review
