Repository adambard/learnxinyminutes-docs, pull requests merged in 2018-09, with the labels that each got.

#3129 [Swift/zh-cn] update to swift 4.1
  zh-cn/swift-cn.html.markdown
Labels: awaiting response

#3209 [PyQT/FR] Add french translation PyQT
  fr-fr/pyqt-fr.html.markdown
Labels: awaiting response, translation

#3203 [C/zh-cn] Fix typos
  zh-cn/c-cn.html.markdown
Labels: awaiting response

#3211 [typescript/zh-cn] Fix space style and little content
  zh-cn/typescript-cn.html.markdown
Labels: awaiting response

#3153 [awk/zh-cn] translate awk to Chinese(zh-cn)
  zh-cn/awk-cn.html.markdown
Labels: awaiting response, translation

#3113 [commonlisp/ru-ru] Added russian translation
  ru-ru/common-lisp-ru.html.markdown
Labels: awaiting response, translation

#3214 [language/kotlin] Update kotlin.html.markdown
  kotlin.html.markdown
Labels: awaiting response

#3224 The source code can be run by Rust Playground
  rust.html.markdown
Labels: work in progress

#3225 Create traslation rust.html.markdown to Russian
  ru-ru/rust-ru.html.markdown
Labels: work in progress

#3222 [fsharp/en] Add note on equality operator
  fsharp.html.markdown
Labels: work in progress

#3104 [clojure-macros/ms-my] Added Malay translation for clojure macros
  ms-my/clojure-macros-my.html.markdown
Labels: awaiting response, translation

#3105 [common-lisp/ms-my] Added Malay translation for Common Lisp
  ms-my/common-lisp-my.html.markdown
Labels: awaiting response, translation

#3106 [elisp/ms-my] Add Malay translation for Elisp
  ms-my/elisp-my.html.markdown
Labels: awaiting response, translation
