Repository adambard/learnxinyminutes-docs, pull requests merged in 2018-12, with the labels that each got.

#3417 [common-lisp/es] Spanish Translation for Common Lisp
  es-es/common-lisp-es.html.markdown
Labels: translation

#3418 [php-composer/ru] Update Russian translation for Composer
  ru-ru/php-composer-ru.html.markdown
Labels: translation update

#3419 [yaml/en] Removed duplicate is in YAML docs
  yaml.html.markdown
Labels: quickfix

#3420 Create yaml-ru.html.markdown
  ru-ru/yaml-ru.html.markdown
Labels: awaiting response, translation

#3421 [sl-si/asciidoc] Add Slovenian translation for AsciiDoc
  sl-si/asciidoc-sl.html.markdown
Labels: in review, translation

#3429 [asymptotic-notation/ru] Proofreading
  ru-ru/asymptotic-notation-ru.html.markdown
Labels: translation update

#3430 [bash/ru] Sync with English original
  ru-ru/bash-ru.html.markdown
Labels: translation update

#3432 [solidity/en,cn] Solidity code should not be mixed with Javascript code
  solidity.html.markdown
  zh-cn/solidity-cn.html.markdown
Labels: in review

#3436 elixir/en
  elixir.html.markdown
Labels: in review
