Repository adambard/learnxinyminutes-docs, pull requests merged in 2018-10, with the labels that each got.

#3221 Learn Erlang in Spanish
  es-es/erlang-es.html.markdown
Labels: work in progress

#3254 [textile/en] add textile #2994
  textile.html.markdown
Labels: awaiting response, work in progress

#3257 [crystal/ru] Add Russian translation for Crystal
  ru-ru/crystal-ru.html.markdown
Labels: translation, work in progress

#3271 [Lambda Calculus/en] - Closes #3114 - Fixes lambda calculus evaluation formula by fixing associativity
  lambda-calculus.html.markdown
Labels: work in progress

#3275 Make description of static keyword stronger, closes #2848
  c.html.markdown
Labels: work in progress

#3286 [cmake/pt-br] Add portuguese language for cmake
  pt-br/cmake-pt.html.markdown
Labels: translation

#3291 [jquery/it-IT] Add italian language for jquery
  it-it/jquery-it.html.markdown
Labels: translation

#3290 [pyqt/it-IT] Add italian language for pyqt
  it-it/pyqt-it.html.markdown
Labels: translation

#3289 [asciidoc/it-IT] Add italian language for asciidoc
  it-it/asciidoc-it.html.markdown
Labels: translation

#3288 [qt/it-IT] Add italian language for qt
  it-it/qt-it.html.markdown
Labels: translation

#3294 [dynamic-programming/nl-nl] Add Dutch language for dynamic-programming
  nl-nl/dynamic-programming-nl.html.markdown
Labels: translation

#3292 [toml/it] Add it-IT translation for TOML
  it-it/toml-it.html.markdown
Labels: translation

#3298 [ruby/it] Translation of Ruby in Italian
  it-it/ruby-it.html.markdown
Labels: translation

#3299 [javascript/cz] improve wording, fix typos, add missing text from English original
  cs-cz/javascript.html.markdown
Labels: translation update

#3308 [opencv/de] Translate opencv to german
  de-de/opencv-de.html.markdown
Labels: in review, translation

#3311 [shutit/de] Translate shutit to german
  de-de/shutit-de.html.markdown
Labels: in review, translation

#3309 [hq9+/de] Translate hq9+ to german
  de-de/hq9+-de.html.markdown
Labels: in review, translation

#3310 [rst/de] Translate rst to german
  de-de/rst-de.html.markdown
Labels: in review, translation

#3307 [paren/de] Translate paren to german
  de-de/paren-de.html.markdown
Labels: in review, translation

#3313 [typescript/en] Add example of "implements" keyword
  typescript.html.markdown
Labels: in review

#3312 [de-de/opencv] Added another good Tutorial source, fixed word consistency
  de-de/opencv-de.html.markdown
Labels: in review

#3318 [jquery/en] Added a resource (tutorial)
  jquery.html.markdown
Labels: in review

#3317 [json/en] Added a resource (tutorial)
  json.html.markdown
Labels: in review

#3316 [git/en] Added a resource (tutorial)
  git.html.markdown
Labels: in review

#3314 [vim/nl-nl]Add Dutch Vim translation
  nl-nl/vim-nl.html.markdown
Labels: in review, translation

#3315 [less/pt-br] Add portuguese language for less
  pt-br/less-pt.html.markdown
Labels: in review, translation

#3319 [make/pt-br] Add portuguese language for make
  pt-br/make-pt.html.markdown
Labels: in review, translation

#3320 [cypher/pt-br] Add portuguese language for cypher
  pt-br/cypher-pt.html.markdown
Labels: in review, translation

#3323 [c++/en] efficient typo fix
  c++.html.markdown
Labels: quickfix

#3325 [Tcl/en] update tcl hyperlinks
  tcl.html.markdown
Labels: quickfix

#3322 [factor/pt-br] Add portuguese language for factor
  pt-br/factor-pt.html.markdown
Labels: in review, translation, work in progress

#3256 [julia/en] fix for #1483
  julia.html.markdown
Labels: work in progress

#3326 [pcre/it] Add pcre-it.html.markdown
  it-it/pcre-it.html.markdown
Labels: in review, translation

#3324 [typescript/it] Add typescript-it.html.markdown
  it-it/typescript-it.html.markdown
Labels: translation

#3043 [bash/en] Add string length & regex code
  bash.html.markdown
Labels: awaiting response

#3102 LogTalk tutorial in Bulgarian
  bg-bg/logtalk-bg.html.markdown
Labels: awaiting response

#3103 [latex/en-en] Fix paragraph separation, inter-word space, add microtype package
  latex.html.markdown
Labels: in review

#3334 [python/cz] Fix text, closes #3023
  cs-cz/python3.html.markdown
Labels: translation update

#3077 [ansible/en-en] Ansible - request for a review
  ansible.html.markdown
Labels: awaiting response

#2948 [matlab/es-es] Translate MatLab to es_ES
  es-es/matlab-es.html.markdown
Labels: in review, translation, work in progress

#3339 Add the distributed source control management tool mercurial.
  mercurial.html.markdown
Labels: in review

#3344 [pyqt/es-es] PyQT Spanish translation
  es-es/pyqt-es.html.markdown
Labels: awaiting response, translation, work in progress

#3355 [mercurial/en] Multiple fixes
  mercurial.html.markdown
Labels: work in progress

#3351 [clojure-macros] Fixed links
  clojure-macros.html.markdown
Labels: work in progress

#3367 [csharp/pt-br] Missing translation
  pt-br/csharp-pt.html.markdown
Labels: in review, translation update

#3368 [csharp/pt-br] Update csharp-pt.html.markdown
  pt-br/csharp-pt.html.markdown
Labels: in review, translation update

#3369 [csharp/pt-br] Update csharp-pt.html.markdown
  pt-br/csharp-pt.html.markdown
Labels: in review, translation update

#3370 [csharp/pt-br] Update csharp-pt.html.markdown
  pt-br/csharp-pt.html.markdown
Labels: in review, translation update

#3365 [typescript/pt-br] Removed duplicate text
  pt-br/typescript-pt.html.markdown
Labels: in review, translation update

#3366 [ruby/pt-br] Update ruby-pt.html.markdown
  pt-br/ruby-pt.html.markdown
Labels: in review, translation update

#3372 [xml/pt-bt] Better translation
  pt-br/xml-pt.html.markdown
Labels: in review, translation update

#3373 [whip/pt-br] Better translation
  pt-br/whip-pt.html.markdown
Labels: in review, translation update

#3375 [paren/pt-br] Small typos
  pt-br/paren-pt.html.markdown
Labels: in review, translation update

#3374 [csharp/pt-br] Missing translation
  pt-br/csharp-pt.html.markdown
Labels: in review, translation update

#3371 [yaml/pt-br] Fixing translation
  pt-br/yaml-pt.html.markdown
Labels: translation update, work in progress
