Repository adambard/learnxinyminutes-docs, pull requests merged in 2019-08, with the labels that each got.

#3547 [pug/en] Add Pug language tutorial
  pug.html.markdown
Labels: new article

#3549 scala/es
  es-es/scala-es.html.markdown
Labels: translation

#3519 [bc/en] New tutorial
  bc.html.markdown
Labels: in review

#3534 [dart/es]
  es-es/dart-es.html.markdown
Labels: translation

#3531 [Markdown/zh-cn] More Examples and visualization
  zh-cn/markdown-cn.html.markdown
Labels: enhancement

#3532 [Lambda calculus/zh-cn] Add Chinese translation of lambda calculus.
  zh-cn/lambda-calculus-cn.html.markdown
Labels: awaiting response, translation

#3578 [asciidoc/ja-jp]Add translate for AsciiDoc in ja-jp
  ja-jp/asciidoc.html.markdown
Labels: awaiting response, translation

#3562 [emacs/en] Basic Emacs tutorial
  emacs.html.markdown
Labels: awaiting response

#3553 [Swift/en] Update to Swift 5 and include omitted examples
  swift.html.markdown
Labels: enhancement

#3577 [opengl/en] Add Basic OpenGL 3.3+
  opengl.html.markdown
Labels: new article

#3552 [linker/ru] Add description of linker script
  ru-ru/linker-ru.html.markdown
Labels: awaiting response, don't merge, new article

#3545 [dhall/en] Add "Learn Dhall in Y minutes"
  dhall.html.markdown
Labels: new article

#3588 [html/gr] Add greek translation for the HTML language
  el-gr/html-gr.html.markdown
  html.html.markdown
Labels: translation

#3576 [reason/en] Add Reason language
  reason.html.markdown
Labels: awaiting response, new article

#3569 [webassembly/en] added WebAssembly tutorial
  wasm.html.markdown
Labels: awaiting response

#3508 [javascript/it-it] Create javascript-it.html.markdown
  it-it/javascript-it.html.markdown
Labels: awaiting response, work in progress

#3589 [sql/zh-cn] Update Chinese version of SQL.
  zh-cn/sql.html.markdown
Labels: translation

#3604 [typescript/th] finish and up to date for TypeScript's Thai translation
  th-th/typescript.th.html.markdown
Labels: awaiting response, don't merge, translation

#3598 [mercury/en] Added Mercury
  mercury.html.markdown
Labels: awaiting response, don't merge, new article

#3607 [Edn/tr-tr]
  tr-tr/edn-tr.html.markdown
Labels: awaiting response, translation

#3609 Sql file added for Turkish
  tr-tr/sql-tr.html.markdown
Labels: in review

#3481 [sql/ru] SQL full translate
  ru-ru/sql-ru.html.markdown
Labels: in review, translation
