Repository adambard/learnxinyminutes-docs, pull requests merged in 2019-05, with the labels that each got.

#3527 [C++/de] added.
  de-de/c++-de.html.markdown
Labels: work in progress

#3536 [awk/en] add some related links
  awk.html.markdown
Labels: in review

#3540 [rust/it] Fix typo
  it-it/rust-it.html.markdown
Labels: quickfix
