Repository adambard/learnxinyminutes-docs, pull requests merged in 2019-10, with the labels that each got.

#3654 [groovy/pt-br] Small typo
  pt-br/groovy-pt.html.markdown
Labels: quickfix

#3671 [bf/pl-pl] Fix translation
  pl-pl/bf-pl.html.markdown
Labels: quickfix

#3676 [sql/ru] Fix translation
  ru-ru/sql-ru.html.markdown
Labels: translation update

#3680 [wasm/ua] Add translation
  uk-ua/python-ua.html.markdown
  uk-ua/wasm.html.markdown
Labels: translation

#3682 [wasm/ua] Fix lang param
  uk-ua/wasm-ua.html.markdown
Labels: quickfix

#3696 [kotlin/ru-ru] fix typo
  ru-ru/kotlin-ru.html.markdown
Labels: quickfix

#3742 [LaTeX and λ/lsf] Add a new language
  lsf/lambda-calculus-lsf.html.markdown
  lsf/latex-lsf.html.markdown
Labels: translation

#3739 [kotlin/uk-ua] Add ukrainian translation for Kotlin
  uk-ua/kotlin-ua.html.markdown
Labels: translation

#3747 [cypher/uk-ua] Add ukrainian translation for Cypher query language
  uk-ua/cypher-ua.html.markdown
Labels: awaiting response, translation
