Repository adambard/learnxinyminutes-docs, pull requests merged in 2019-03, with the labels that each got.

#3482 [awk/fr] add awk-fr.html.markdown
  fr-fr/awk-fr.html.markdown
Labels: translation

#3489 [c++/en] Typo in c++
  c++.html.markdown
Labels: quickfix

#3488 [Global] Update tools category
  CONTRIBUTING.markdown
  awk.html.markdown
  cmake.html.markdown
  de-de/make-de.html.markdown
  es-es/awk-es.html.markdown
  es-es/pythonstatcomp-es.html.markdown
  fr-fr/awk-fr.html.markdown
  fr-fr/make-fr.html.markdown
  make.html.markdown
  pt-br/awk-pt.html.markdown
  pt-br/cmake-pt.html.markdown
  pt-br/make-pt.html.markdown
  tcsh.html.markdown
  zh-cn/awk-cn.html.markdown
  zh-cn/make-cn.html.markdown
Labels: in review

#3496 [java/pl-pl] Full Java translation to Polish
  pl-pl/java-pl.html.markdown
Labels: translation
