Repository adambard/learnxinyminutes-docs, pull requests merged in 2019-02, with the labels that each got.

#3460 [logtalk/en,it-it] Improve section on compiling and loading source files
  it-it/logtalk-it.html.markdown
  logtalk.html.markdown
Labels: quickfix, translation update

#3459 [powershell/en] Fix typo in powershell page
  powershell.html.markdown
Labels: quickfix

#3458 [python/all] Type correction for the output of math.sqrt()
  cs-cz/python3.html.markdown
  de-de/python-de.html.markdown
  de-de/python3-de.html.markdown
  es-es/python-es.html.markdown
  fr-fr/python-fr.html.markdown
  hu-hu/python-hu.html.markdown
  it-it/python-it.html.markdown
  ko-kr/python-kr.html.markdown
  pl-pl/python-pl.html.markdown
  pt-br/python-pt.html.markdown
  pt-br/python3-pt.html.markdown
  python.html.markdown
  ro-ro/python-ro.html.markdown
  ru-ru/python-ru.html.markdown
  tr-tr/python-tr.html.markdown
  uk-ua/python-ua.html.markdown
  zh-cn/python-cn.html.markdown
  zh-tw/python-tw.html.markdown
Labels: awaiting response, quickfix

#3464 [python3/en] Update integer division
  python3.html.markdown
Labels: quickfix

#3465 [python3/ar] Learn python 3 in Y minutes Arabic translation
  ar-ar/python3-ar.html.markdown
Labels: translation

#3466 [pascal/en] Fixed missing escape character
  pascal.html.markdown
Labels: in review, quickfix

#3468 [Pascal/pt-br] Translating Pascal guide to Brazilian Portuguese
  pt-br/pascal-pt.html.markdown
Labels: translation

#3407 [lambda-calculus] propose correction for ADD
  lambda-calculus.html.markdown
Labels: quickfix

#3478 [julia/en] Add note about integer overflow
  julia.html.markdown
Labels: quickfix
