Repository adambard/learnxinyminutes-docs, pull requests merged in 2019-11, with the labels that each got.

#3756 [rust/ru-ru] minor fix in translation
  ru-ru/rust-ru.html.markdown
Labels: quickfix

#3752 [Lambda calculus/lsf] Fix line length
  lsf/lambda-calculus-lsf.html.markdown
Labels: quickfix

#3751 [typescript/en] Fix playground link
  typescript.html.markdown
Labels: quickfix

#3737 [go/uk-ua] Add ukrainian translation for Go language
  uk-ua/go-ua.html.markdown
Labels: awaiting response, translation

#3736 [mips/uk-ua] Add ukrainian translation for MIPS Assemly
  uk-ua/mips-ua.html.markdown
Labels: awaiting response, translation

#3764 [bash/de] Fix missing double quotes
  de-de/bash-de.html.markdown
Labels: quickfix

#3769 [python3/en] Fixed a small typo
  python3.html.markdown
Labels: quickfix

#3771 [language/reason] fix typo
  reason.html.markdown
Labels: quickfix

#3766 [C++/de-de] Fixed some typos in german translation
  de-de/c++-de.html.markdown
Labels: awaiting response, translation update

#3773 [c++/ru-ru] Fix multiple minor typos
  ru-ru/c++-ru.html.markdown
Labels: quickfix

#3776 [C#/en] Update some urls
  csharp.html.markdown
Labels: quickfix

#3767 [Rust/ru-ru] Update intro and fix some misspellings (Обновлена вводная часть и исправлены некоторые опечатки)
  ru-ru/rust-ru.html.markdown
Labels: awaiting response, translation update
