Repository adambard/learnxinyminutes-docs, pull requests merged in 2019-01, with the labels that each got.

#3439 [asymptotic-notation/pt-br] fix several typos
  pt-br/asymptotic-notation-pt.html.markdown
Labels: translation update

#3442 [awk/en] fix minor spelling mistakes
  awk.html.markdown
Labels: quickfix

#3445 [ocaml/en] Fix typo
  ocaml.html.markdown
Labels: quickfix

#3446 [stylus/en] Translate stylus into en
  stylus.html.markdown
Labels: translation

#3455 typescript/en Fixes typo
  typescript.html.markdown
Labels: quickfix

#3454 [latex/en] Fix comment on using \ after abbreviations
  latex.html.markdown
Labels: quickfix

#3451 [julia/en] tweak order of string functions / print functions
  julia.html.markdown
Labels: in review

#3452 [javascript/en] Fix prototype example
  javascript.html.markdown
Labels: quickfix
