Repository adambard/learnxinyminutes-docs, pull requests merged in 2020-02, with the labels that each got.

#3738 [markdown/pt-br] Formatting adjustments
  pt-br/markdown-pt.html.markdown
Labels: awaiting response, translation update

#3839 [de-de/c] Translated C to German (See Issue #3592)
  de-de/c-de.html.markdown
Labels: in review

#3820 [dart/en] Update Guide and add more features
  dart.html.markdown
Labels: awaiting response

#3841 Fixed prototype function return value comment in javascript-ru
  ru-ru/javascript-ru.html.markdown
Labels: in review

#3854 [python3/de-de] fixed some small typos in German translation
  de-de/python-de.html.markdown
Labels: work in progress
