Repository adambard/learnxinyminutes-docs, pull requests merged in 2021-08, with the labels that each got.

#4220 [wim/gr] Try fixing display bug
  el-gr/vim-gr.html.markdown
Labels: quickfix

#4214 [MongoDB/en] Add Learn MongoDB in Y Minutes
  mongodb.html.markdown
Labels: new article

#4204 Fix JSON code blocks in TOML
  toml.html.markdown
Labels: quickfix

#3762 [c/uk-ua] Add ukrainian translation for Clang
  uk-ua/c-ua.html.markdown
Labels: translation, in review
