Repository adambard/learnxinyminutes-docs, pull requests merged in 2024-04, with the labels that each got.

#4369 [html/ru-ru]: make spellcheck in file
  ru-ru/html-ru.html.markdown
Labels: help wanted

#3710 [sql/de] Translate sql to german
  de-de/sql-de.html.markdown
Labels: awaiting response

#3748 [haskell/el-gr] Add Greek translation for Haskell
  el-gr/haskell-gr.html.markdown
Labels: awaiting response

#3972 [c/fr] C French translation
  fr-fr/c-fr.html.markdown
Labels: abandoned?
